// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://febvdnchgbvrwcejgvse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlYnZkbmNoZ2J2cndjZWpndnNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTkxODgsImV4cCI6MjA2NDc5NTE4OH0.tujCSnBwGEr2m4mpTP5pcjjISqscRDEDPCw34ZxqM3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);